spring.cloud.config.server:
  git:
     uri: https://github.com/cjrequena/config-repo
     #username: gitusername
     #password: gitpassword
     basedir: target/config

spring.cloud.bus:
  enabled: true
spring.cloud.stream:
  kafka:
    binders:
      zkNodes: localhost
      defaultZkPort: 2181
      brokers: localhost
      defaultBrokerPort: 9092

#-----------------------------------------------------------------------------------------------
# Logging configuration
#-----------------------------------------------------------------------------------------------
logging:
  level:
    org.springframework: 'WARN'
    org.springframework.cloud: 'DEBUG'
    com.netflix.discovery: 'OFF'
    com.sample: DEBUG
  pattern:
    console: '%highlight{%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=blue bold, DEBUG=green bold, TRACE=blue}'
    file: '%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n'
  config: classpath:log4j2-local.xml
