spring.cloud.config.server.git.uri: https://github.com/cjrequena/config-repo # The URI of the Git Repository where the configuration is stored
#spring.cloud.config.server.git.username: gitusername
#spring.cloud.config.server.git.password: gitpassword
spring.cloud.config.server.bootstrap: true # Whether the Spring Cloud Config Server should configure iteslf with the loaded configuration.

# Change replication through kafka.
spring.cloud.bus.enabled: true
spring.cloud.stream.kafka:
  binders:
    zkNodes: 127.0.0.1
    defaultZkPort: 2181
    brokers: 127.0.0.1
    defaultBrokerPort: 9092

# Logging
logging.config: classpath:log4j2-spring.xml # Location of the logging configuration file. For instance, `classpath:logback.xml` for Logback.
logging.file: log4j2-spring.xml # Log file name (for instance, `myapp.log`). Names can be an exact location or relative to the current directory.
logging.level: # Log levels severity mapping. For instance, `logging.level.org.springframework: DEBUG`.
  org.springframework: INFO
  com.sample: DEBUG
  org.I0Itec.zkclient.ZkConnection: ERROR
